apiVersion: v2
name: antmedia
description: A Helm chart for Kubernetes
type: application
version: 2.5.5
appVersion: "1.5.1"

dependencies:
  - name: ingress-nginx
    version: "<= 4.4.0"
    repository: https://kubernetes.github.io/ingress-nginx

maintainers:
  - name: muratugureminoglu
    email: murat@murat.ws
