# Default values for antmedia-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: antmedia/enterprise
  tag: 2.5.3
  pullPolicy: IfNotPresent


autoscalingEdge:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

autoscalingOrigin:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  
origin: origin.antmedia.cloud
edge: edge.antmedia.cloud
mongoDB: mongo

hostNetwork: true

provider:
  aws: false
  default: true
